// <auto-generated />
using System;
using EidolonicBot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EidolonicBot.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20250901153436_MigrateToLabelsDbSet")]
    partial class MigrateToLabelsDbSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("EidolonicBot.Models.LabelByChat", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId", "MessageThreadId", "Address");

                    b.ToTable("LabelByChat");
                });

            modelBuilder.Entity("EidolonicBot.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("EidolonicBot.Models.SubscriptionByChat", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinDelta")
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId", "MessageThreadId", "SubscriptionId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionByChat");
                });

            modelBuilder.Entity("EidolonicBot.Models.SubscriptionByChat", b =>
                {
                    b.HasOne("EidolonicBot.Models.Subscription", "Subscription")
                        .WithMany("SubscriptionByChat")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("EidolonicBot.Models.Subscription", b =>
                {
                    b.Navigation("SubscriptionByChat");
                });
#pragma warning restore 612, 618
        }
    }
}
