ARG BASE_IMAGE=mcr.microsoft.com/dotnet/runtime:8.0-bookworm-slim

FROM ${BASE_IMAGE}

RUN apt update \
    && apt install -y wget \
    && rm -rf /var/lib/apt/lists/*

RUN TEMP_DEB="$(mktemp)" && \
    wget -O "$TEMP_DEB" "http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.1_1.1.1n-0+deb10u6_$(dpkg --print-architecture).deb" && \
    dpkg -i "$TEMP_DEB"
