name: 'Build dotnet runtime with libssl1.1'

on:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  RUNTIME_BASE_IMAGE: dotnet/runtime
  RUNTIME_BASE_IMAGE_TAG: 8.0-bookworm-slim
  IMAGE_NAME: ${{ github.repository }}
  ARCH_PLATFORMS: x64-amd64,arm64-arm64
jobs:
  build:
    name: Build and Push runtime image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/dotnet-runtime
          tags: |
            type=raw,value=${{ env.RUNTIME_BASE_IMAGE_TAG }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      
      - name: Build and push runtime with libssl1.1
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.runtime
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: mcr.microsoft.com/${{ env.RUNTIME_BASE_IMAGE }}:${{ env.RUNTIME_BASE_IMAGE_TAG }}
      
      # die to dotnet publish cant pull image by manifest from ghcr.io
      - name: Push dotnet-runtime by arch
        run: |
          for arch in amd64 arm64; do
            docker pull --platform=linux/$arch ${{ env.REGISTRY }}/${{ github.repository_owner }}/dotnet-runtime:${{ env.RUNTIME_BASE_IMAGE_TAG }}
            docker tag ${{ env.REGISTRY }}/${{ github.repository_owner }}/dotnet-runtime:${{ env.RUNTIME_BASE_IMAGE_TAG }} ${{ env.REGISTRY }}/${{ github.repository_owner }}/dotnet-runtime:${{ env.RUNTIME_BASE_IMAGE_TAG }}-$arch
            docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/dotnet-runtime:${{ env.RUNTIME_BASE_IMAGE_TAG }}-$arch
          done
