name: Hosting

on:
  push:
    paths:
      - .github/workflows/hosting.yaml
    branches:
      - main
  schedule:
    - cron: '0 */4 * * *'
  workflow_run:
    workflows: [ CI ]
    types: [ completed ]
    branches: [ main ]
  workflow_dispatch:

env:
  HOSTING_PATH: .hosting

jobs:
  run-app:
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        working-directory: ${{ env.HOSTING_PATH }}
        run: |
          cat <<EOT > .env
          Bot__Token=${{ secrets.BOT_TOKEN }}
          Wallet__SeedPhrase=${{ secrets.WALLET_SEED_PHRASE }}
          EverClient__Network__Endpoints__0=${{ secrets.NETWORK_ENDPOINT }}
          Serilog__WriteTo__Elasticsearch__Args__nodeUris=${{ secrets.SEMATEXT_ELASTICSEARCH_URIS }}
          SENTRY_DSN=${{ secrets.SENTRY_DSN }}
          ConnectionStrings__Postgres=${{ secrets.SUPABASE_CONNECTION_STRING }}
          AMQP_URI=${{ secrets.AMQP_URI }}
          EOT

      - uses: nrwl/last-successful-commit-action@v1
        id: last_successful_commit
        with:
          branch: 'main'
          workflow_id: 'ci.yaml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run app
        working-directory: ${{ env.HOSTING_PATH }}
        run: |
          TAG=${{ steps.last_successful_commit.outputs.commit_hash }} docker compose up --pull=always

      - name: Logs to artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: .hosting/logs/**